name: BedrockFormShop
version: '${project.version}'
main: dev.kejona.bedrockformshop.BedrockFormShop
api-version: 1.15
depend: [ floodgate, Vault ]
authors: [ kejonaMC ]
commands:
  bshop:
    description: Open Shop
    permission: bedrockformshop.openshop
    default: true
    aliases: /bshop
permissions:
  bedrockformshop.openshop:
    description: "Open Shop"
    default: true
  bedrockformshop.playermenu:
    description: "Display Player Buttons"
    default: true
  bedrockformshop.adminmenu:
    description: "Display Admin Buttons"
    default: op
  bedrockformshop.reload:
    description: "Reload Config"
    default: op
  bedrockformshop.*:
    description: "Give all permissions"
    default: op

